name: Link to hyponome
on:
  pull_request_target:
    types: [opened]
    paths:
      - 'step-templates/**'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Review this PR in [Hyponome](https://octopusdeploy.github.io/Library/pr-review/#/pulls/${context.issue.number}) for a side-by-side diff of the step-template JSON and any embedded scripts.`
            })
